name: Publish to Maven Central Staging

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  gradle-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Determines version from tag
        id: version
        run: |
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Build and test
        run: ./gradlew build
      - name: Publish and release to Maven Central
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.version.outputs.VERSION }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.PGP_SECRET }}
        run: ./gradlew publishToMavenCentral --no-configuration-cache
